# Generated by Django 4.1.1 on 2022-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(choices=[('Cr_Up', 'created/updated'), ('Del', 'deleted')], max_length=5)),
                ('model', models.CharField(max_length=40)),
                ('to_related', models.CharField(max_length=40)),
                ('publication_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
