# Generated by Django 4.1.1 on 2022-11-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_logactivity_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logactivity',
            name='user_id',
        ),
        migrations.AddField(
            model_name='logactivity',
            name='user',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
