# Generated by Django 4.1.1 on 2022-11-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_logactivity_user_id_logactivity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
