# Generated by Django 4.1.1 on 2022-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_taskcomment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactivity',
            name='model',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='logactivity',
            name='to_related',
            field=models.CharField(max_length=90),
        ),
    ]
