# Generated by Django 4.1.1 on 2022-12-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_logactivity_model_alter_logactivity_to_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logactivity',
            options={'ordering': ['-publication_date_time']},
        ),
    ]
