# Generated by Django 4.1.1 on 2022-10-27 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_buildinproject_options_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_check', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_designer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='is_issued',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='is_ready_for_markups',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='projects.buildinproject'),
            preserve_default=False,
        ),
    ]
