# Generated by Django 4.1.1 on 2022-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task_id',
            field=models.CharField(max_length=30),
        ),
    ]
