# Generated by Django 4.1.1 on 2022-10-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_projecttask_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='designer',
        ),
    ]
