# Generated by Django 4.1.1 on 2022-10-27 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_projecttask_checked_by_projecttask_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_checker', to=settings.AUTH_USER_MODEL),
        ),
    ]
