# Generated by Django 4.1.1 on 2022-10-27 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_projecttask_checked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='time_estimation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
