# Generated by Django 4.1.1 on 2022-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_projecttask_time_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='is_issued',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='is_ready_for_markups',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
