version: '3.4'

services:
  web:
    image: tangelova123/buildin
    build: .
    command: gunicorn buildin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static_files:/tmp/buildin/staticfiles
    ports:
      - 8000:8000
    env_file:
      - envs/.env.prod
    depends_on:
      - postgres
  postgres:    
    image: postgres
    restart: always

    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: buildin_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./static_files:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web