# Generated by Django 4.1.1 on 2022-10-09 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('participant_role', models.CharField(choices=[('Contractor', 'Contractor'), ('Designer', 'Designer'), ('Builder', 'Builder'), ('Designer', 'Designer')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
