# Generated by Django 4.1.1 on 2022-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='participant_role',
            field=models.CharField(choices=[('INTERN', 'Intern design engineer'), ('JN_ENG', 'Junior design engineer'), ('MID_ENG', 'Mid design engineer'), ('SN_ENG', 'Senior design engineer'), ('LEAD', 'Team Lead')], max_length=7),
        ),
    ]
