# Generated by Django 4.1.1 on 2022-11-12 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_identifier', models.CharField(max_length=40)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_phase', models.CharField(blank=True, choices=[('RandD', 'RD'), ('PD', 'PD'), ('SD', 'SD'), ('DD', 'DD'), ('CD', 'CD'), ('OTHER', 'Other')], max_length=5, null=True)),
                ('client_name', models.CharField(blank=True, max_length=35, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('project_img', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('project_identifier',),
            },
        ),
    ]
