# Generated by Django 4.1.1 on 2022-10-09 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_identifier', models.CharField(max_length=40)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_phase', models.CharField(choices=[('RD', 'R&D'), ('PD', 'Preliminary design'), ('SD', 'Schematic Design'), ('DD', 'Design Development'), ('CD', 'Construction Documentation'), ('Other', 'Other')], default='PD', max_length=5)),
                ('client_name', models.CharField(blank=True, max_length=35, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('project_img', models.URLField(default='https://unsplash.com/photos/VYqkeRANz90')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
