# Generated by Django 4.1.1 on 2022-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinproject',
            name='project_img',
            field=models.URLField(default='https://unsplash.com/photos/VYqkeRANz90'),
        ),
    ]
