# Generated by Django 4.1.1 on 2022-10-27 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_buildinproject_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinproject',
            options={'ordering': ('project_identifier',)},
        ),
        migrations.AddField(
            model_name='buildinproject',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildinproject',
            name='project_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
